# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0f6d595dfb16e90e25296a671343cede83f4ed9501e4ad1729cde025fcf4af48b8655d8fb2c93e8aa12e37f66abe71e2b35c07d8081ca1da0dd491c4a88ce3d

test:
  secret_key_base: 23067d9037e8457049b1ce23c9e9c3889ddeee3caa429c7c368fdedc72f0efde1a9343df6120fffdf3a25f069bf9752efa4ed7d4c85ad8cba682ee5cf60882cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
